list: $/alex/cert/models/cert/columns.yaml
modelClass: Alex\Cert\Models\Cert
title: Cert
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'alex/cert/cert/update/:id'
