list: $/alex/about/models/about/columns.yaml
modelClass: Alex\About\Models\About
title: About
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'alex/about/about/update/:id'
