list: $/alex/mission/models/mission/columns.yaml
modelClass: Alex\Mission\Models\Mission
title: Mission
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'alex/mission/mission/update/:id'
