list: $/alex/contact/models/contact/columns.yaml
modelClass: Alex\Contact\Models\Contact
title: Contact
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'alex/contact/contact/update/:id'
