list: $/alex/news/models/news/columns.yaml
modelClass: Alex\News\Models\News
title: News
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'alex/news/news/update/:id'
