list: $/alex/vakansii/models/vakansii/columns.yaml
modelClass: Alex\Vakansii\Models\Vakansii
title: Vakansii
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'alex/vakansii/vakansii/update/:id'
