list: $/alex/brand/models/brand/columns.yaml
modelClass: Alex\Brand\Models\Brand
title: Brand
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'alex/brand/brand/update/:id'
