list: $/alex/opitimg/models/opitimg/columns.yaml
modelClass: Alex\Opitimg\Models\Opitimg
title: Opitimg
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'alex/opitimg/opitimg/update/:id'
