list: $/alex/uslugi/models/uslugi/columns.yaml
modelClass: Alex\Uslugi\Models\Uslugi
title: Uslugi
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'alex/uslugi/uslugi/update/:id'
